sonar.projectKey=ProyectoPos
sonar.projectName=ProyectoPos

# Carpetas con código propio
sonar.sources=controllers,models,views,config,services,includes,assets

# Excluir librerías externas y archivos subidos
sonar.exclusions=fpdf/**,libraries/**,PHPMailer/**,uploads/**,*.pdf
sonar.token=sqp_2926c353dbe11834c76267e18d2e70fe2f525a5d
